---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-backend

spec:
  replicas: 1

  template:
    spec:
      serviceAccountName: nginx-backend

      containers:
        - name: server
          image: nginx-backend
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: http

          readinessProbe:
            httpGet:
              path: /healthz
              port: http

...
