---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-backend
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: backend

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: backend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/component: backend

    spec:
      serviceAccountName: nginx-backend

      containers:
        - name: server
          image: nginx-backend
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics

          readinessProbe:
            httpGet:
              path: /readyz
              port: metrics

...
