---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - service.yml
  - deployment.yml

images:
  - name: nginx-backend
    newName: quay.io/webhippie/errors
    newTag: "1.0.1"

...
