---
apiVersion: v1
kind: Service

metadata:
  name: nginx-backend
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: backend

spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: backend

  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 8081
      targetPort: metrics

...
