---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: nginx-webhook

rules:
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - "validatingwebhookconfigurations"
    verbs:
      - "get"
      - "update"

...
