---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: nginx-webhook
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: webhook

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-webhook

subjects:
  - kind: ServiceAccount
    name: nginx-webhook

...
