---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml

  - validatingwebhook.yml
  - job.yml

commonLabels:
  app.kubernetes.io/component: webhook

...
