---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: nginx-webhook

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-webhook

subjects:
  - kind: ServiceAccount
    name: nginx-webhook

...
