---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: nginx-webhook

rules:
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"

...
