---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration

metadata:
  name: nginx-webhook

webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        namespace: ingress-nginx
        name: nginx-webhook
        path: /networking/v1beta1/ingresses
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: validate.nginx.ingress.kubernetes.io
    rules:
      - apiGroups:
          - networking.k8s.io
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - ingresses
    sideEffects: None
    timeoutSeconds: 10

...
