---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml
  - service.yml
  - daemonset.yml
  - ingressclass.yml

configMapGenerator:
  - name: nginx-tcp
    literals: []
  - name: nginx-udp
    literals: []
  - name: nginx-config
    literals:
      - server-tokens=false

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: nginx-controller
    newName: registry.k8s.io/ingress-nginx/controller
    newTag: "v1.8.0"

...
