---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - role.yml
  - rolebinding.yml

  - service.yml
  - daemonset.yml

commonLabels:
  app.kubernetes.io/component: controller

configMapGenerator:
  - name: nginx-tcp
    literals: []
  - name: nginx-udp
    literals: []
  - name: nginx-config
    literals:
      - server-tokens=false

generatorOptions:
  disableNameSuffixHash: true

...
