---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: nginx-controller
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-controller

subjects:
  - kind: ServiceAccount
    name: nginx-controller

...
