---
apiVersion: v1
kind: Service

metadata:
  name: nginx-ingress
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

spec:
  externalTrafficPolicy: Local
  type: NodePort

  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

  ports:
    - name: http
      nodePort: 30080
      port: 80
    - name: https
      nodePort: 30443
      port: 443

...
---
apiVersion: v1
kind: Service

metadata:
  name: nginx-metrics
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

  ports:
    - name: metrics
      port: 10254
      targetPort: metrics

...
---
apiVersion: v1
kind: Service

metadata:
  name: nginx-webhook
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller

  ports:
    - name: webhook
      port: 443
      targetPort: webhook

...
